package edu.iit.tse.transvis.experimentui.tripgeneration;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 *
 * @author debabrata
 */
public class DataAnalysisPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel1
     */
    List<String> list1;
    List<String> list2;

    public DataAnalysisPanel(ArrayList<String> list1, ArrayList<String> list2) {
        this.list1 = list1;
        this.list2 = list2;
        initComponents();
    }

    public void setList1(List<String> list1) {
        this.list1 = list1;
        System.out.println("The Header information of the file is ");
        for (String temp : this.list1) {
            System.out.println(temp);
        }
        jXList1.updateUI();
        jScrollPane2.updateUI();
    }

    public void setList2(ArrayList<String> list2) {
        this.list2 = list2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jXList1 = new org.jdesktop.swingx.JXList();
        jScrollPane5 = new javax.swing.JScrollPane();
        jXList2 = new org.jdesktop.swingx.JXList();

        jButton1.setText(org.openide.util.NbBundle.getMessage(DataAnalysisPanel.class, "DataAnalysisPanel.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText(org.openide.util.NbBundle.getMessage(DataAnalysisPanel.class, "DataAnalysisPanel.jButton4.text")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jXList1.setModel(new javax.swing.AbstractListModel() {
            public int getSize() {
                if(list1 == null) {
                    System.out.println(list1);
                    return 0;
                }
                return list1.size(); }
            public Object getElementAt(int i) { return list1.get(i); }
        });
        jScrollPane2.setViewportView(jXList1);

        jXList2.setModel(new javax.swing.AbstractListModel() {
            public int getSize() {
                if(list2 == null) {
                    System.out.println(list1);
                    return 0;
                }
                return list2.size(); }
            public Object getElementAt(int i) { return list2.get(i); }
        });
        jScrollPane5.setViewportView(jXList2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, Short.MAX_VALUE))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //get the selected value from jlist1
        List<String> list11 = new ArrayList<String>();
        selectedValues = Arrays.asList(jXList1.getSelectedValues()).toArray(new String[jXList1.getSelectedValues().length]);
        //get all the value from jxlist2
        //checking for duplicate and create a newlist where U keep one copy of the value and remove the all Selected value
        //form jxList1 and finally update the value
        //create a new list for list1 and list2
        int[] internal = new int[selectedValues.length];
        for (int _i = 0; _i < selectedValues.length; _i++) {
            for (int __i = 0; __i < list2.size(); __i++) {
                if (selectedValues[_i].equals(list2.get(__i))) {
                    internal[_i] = 1;
                }
            }
        }
        for (int _k = 0; _k < internal.length; _k++) {
            if (internal[_k] == 0) {
                //copy
                list2.add(selectedValues[_k]);
            }
        }
        //newlist1 will be set to jxlist2
        //The element to be removed from list1
        for (int i = 0; i < selectedValues.length; i++) {
            if (internal[i] == 0) {
                //donot delete
                String value = selectedValues[i];
                System.out.println("Debab");
                list1.remove(value);
            }
        }
        jXList1.updateUI();
        jXList2.updateUI();
    }//GEN-LAST:event_jButton4ActionPerformed
    private String[] selectedValues;

    public String[] getSelectedValues() {
        return selectedValues;
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //get the selected value from jlist1
        selectedValues = Arrays.asList(jXList2.getSelectedValues()).toArray(new String[jXList2.getSelectedValues().length]);
        int[] internal = new int[selectedValues.length];
        for (int _i = 0; _i < selectedValues.length; _i++) {
            for (int __i = 0; __i < list1.size(); __i++) {
                if (selectedValues[_i].equals(list1.get(__i))) {
                    internal[_i] = 1;
                }
            }
        }
        for (int _k = 0; _k < internal.length; _k++) {
            if (internal[_k] == 0) {
                //copy
                list1.add(selectedValues[_k]);
            }
        }
        //newlist1 will be set to jxlist2
        //The element to be removed from list1
        for (int i = 0; i < selectedValues.length; i++) {
            if (internal[i] == 0) {
                //donot delete
                String value = selectedValues[i];
                System.out.println("Debab");
                list2.remove(value);
            }
        }
        jXList1.updateUI();
        jXList2.updateUI();
    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private org.jdesktop.swingx.JXList jXList1;
    private org.jdesktop.swingx.JXList jXList2;
    // End of variables declaration//GEN-END:variables
}
