/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.iit.tse.transvis.experimentui.tripgeneration;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 *
 * @author debabrata
 */
public class RegressionAnalysisPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegressionAnalysisPanel
     */
    ArrayList<String> list1; //model for list1
    List<String> list2;

    public RegressionAnalysisPanel(ArrayList<String> list1, List<String> list2) {
        this.list1 = list1;
        this.list2 = list2;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jXList2 = new org.jdesktop.swingx.JXList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jXList1 = new org.jdesktop.swingx.JXList();
        jSeparator2 = new javax.swing.JSeparator();

        jButton1.setText(org.openide.util.NbBundle.getMessage(RegressionAnalysisPanel.class, "RegressionAnalysisPanel.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(org.openide.util.NbBundle.getMessage(RegressionAnalysisPanel.class, "RegressionAnalysisPanel.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1.setText(org.openide.util.NbBundle.getMessage(RegressionAnalysisPanel.class, "RegressionAnalysisPanel.jTextField1.text")); // NOI18N

        jButton3.setText(org.openide.util.NbBundle.getMessage(RegressionAnalysisPanel.class, "RegressionAnalysisPanel.jButton3.text")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText(org.openide.util.NbBundle.getMessage(RegressionAnalysisPanel.class, "RegressionAnalysisPanel.jButton4.text")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setText(org.openide.util.NbBundle.getMessage(RegressionAnalysisPanel.class, "RegressionAnalysisPanel.jLabel1.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(RegressionAnalysisPanel.class, "RegressionAnalysisPanel.jLabel2.text")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(RegressionAnalysisPanel.class, "RegressionAnalysisPanel.jLabel3.text")); // NOI18N

        jXList2.setModel(new javax.swing.AbstractListModel() {
            public int getSize() {
                if(list2 == null) {
                    System.out.println(list2);
                    return 0;
                }
                return list2.size(); }
            public Object getElementAt(int i) { return list2.get(i); }
        });
        jScrollPane1.setViewportView(jXList2);

        jXList1.setModel(new javax.swing.AbstractListModel() {
            public int getSize() {
                if(list1 == null) {
                    System.out.println(list1);
                    return 0;
                }
                return list1.size(); }
            public Object getElementAt(int i) { return list1.get(i); }
        });
        jScrollPane2.setViewportView(jXList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton2)
                                    .addComponent(jButton4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(10, 10, 10))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //get the selected value from jlist1
        List<String> list11 = new ArrayList();
        String selectedValues[] = Arrays.asList(jXList1.getSelectedValues()).toArray(new String[jXList1.getSelectedValues().length]);
        //get all the value from jxlist2
        //checking for duplicate and create a newlist where U keep one copy of the value and remove the all Selected value
        //form jxList1 and finally update the value
        //create a new list for list1 and list2
        int[] internal = new int[selectedValues.length];
        for (int _i = 0; _i < selectedValues.length; _i++) {
            for (int __i = 0; __i < list2.size(); __i++) {
                if (selectedValues[_i].equals(list2.get(__i))) {
                    internal[_i] = 1;
                }
            }
        }
        for (int _k = 0; _k < internal.length; _k++) {
            if (internal[_k] == 0) {
                //copy
                list2.add(selectedValues[_k]);
            }
        }
        //newlist1 will be set to jxlist2
        //The element to be removed from list1
        for (int i = 0; i < selectedValues.length; i++) {
            if (internal[i] == 0) {
                //donot delete
                String value = selectedValues[i];
                list1.remove(value);
            }
        }
        jXList1.updateUI();
        jXList2.updateUI();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //get the selected value from jlist1
        String selectedValues[] = Arrays.asList(jXList2.getSelectedValues()).toArray(new String[jXList2.getSelectedValues().length]);
        int[] internal = new int[selectedValues.length];
        for (int _i = 0; _i < selectedValues.length; _i++) {
            for (int __i = 0; __i < list1.size(); __i++) {
                if (selectedValues[_i].equals(list1.get(__i))) {
                    internal[_i] = 1;
                }
            }
        }
        for (int _k = 0; _k < internal.length; _k++) {
            if (internal[_k] == 0) {
                //copy
                list1.add(selectedValues[_k]);
            }
        }
        //newlist1 will be set to jxlist2
        //The element to be removed from list1
        for (int i = 0; i < selectedValues.length; i++) {
            if (internal[i] == 0) {
                //donot delete
                String value = selectedValues[i];
                list2.remove(value);
            }
        }
        jXList1.updateUI();
        jXList2.updateUI();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String selectedValues[] = Arrays.asList(jXList1.getSelectedValues()).toArray(new String[jXList2.getSelectedValues().length]);
        String selectedValue = selectedValues[0];
        jTextField1.setText(selectedValue);
        list1.remove(selectedValue);
        jXList1.updateUI();
        jXList2.updateUI();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String selectedValue = jTextField1.getText();
        jTextField1.setText("");
        list1.add(selectedValue);
        jXList1.updateUI();
        jXList2.updateUI();
    }//GEN-LAST:event_jButton4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private org.jdesktop.swingx.JXList jXList1;
    private org.jdesktop.swingx.JXList jXList2;
    // End of variables declaration//GEN-END:variables

    public void setList(List<String> list1) {
        this.list1 = (ArrayList<String>) list1;
        System.out.println("The Header information of the file is ");
        for (String temp : this.list1) {
            System.out.println(temp);
        }
        jXList1.updateUI();
        jScrollPane2.updateUI();
    }

}
